font_family Cartograph CF
font_size 13.0
cursor_trail 100
hide_window_decorations yes
tab_bar_style hidden
tab_bar_min_tabs 1
background_opacity 0.5
background_blur 64


# BEGIN_KITTY_THEME
# Matugen
include current-theme.conf
# END_KITTY_THEME

map ctrl+shift+left no_op
map ctrl+shift+right no_op
map ctrl+shift+home no_op
map ctrl+shift+end no_op
