format = '''
$directory$git_branch'''
# $character

palette = 'colors'

[palettes.colors]
mustard = '#af8700' # example
color1 = '#ffb4a7'
color2 = '#561e16'
color3 = '#d8c2be'
color4 = '#271d1c'
color5 = '#561e16'
color6 = '#1a1110'
color7 = '#1a1110'
color8 = '#ffb4a7'
color9 = '#dec48c'

# Prompt symbols 
# [character]
# success_symbol = "[🞈](color9 bold)"
# error_symbol = "[🞈](@{error})"
# vicmd_symbol = "[🞈](#f9e2af)"

[directory]
format = "[](fg:color1 bg:transparent)[󰉋](bg:color1 fg:color2)[ ](fg:color1 bg:color4)[$path ](fg:color3 bg:color4)[ ](fg:color4)"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
format = "[](fg:color1 bg:transparent)[ ](bg:color8 fg:color5)[](fg:color8 bg:color4)[(bg:color8 fg:color5) $branch](fg:color3 bg:color4)[](fg:color4) "

[time]
format = "[](fg:color8 bg:color4)[ ](bg:color8 fg:color5)[](fg:color8 bg:color4)[(bg:color8 fg:color5) $time](fg:color3 bg:color4)[](fg:color4) "
disabled = false
time_format = "%R" # Hour:Minute Format

[python]
format = "[](fg:color8 bg:color4)[${symbol}${version}](bg:color8 fg:color5)[](fg:color8 bg:color4)[(bg:color8 fg:color5)( ${virtualenv})](fg:color3 bg:color4)[](fg:color4) "
symbol = '🐍'
# pyenv_version_name = true
pyenv_prefix = 'venv'
